import { createApp } from "vinxi";
import tsconfigPaths from "vite-tsconfig-paths";
import reactRefresh from "@vitejs/plugin-react";
import { Plugin } from "vite";

const defineConstants: () => Plugin = () => ({
  name: "define-consts",
  config: () => ({
    define: {
      __APP_URL__: JSON.stringify(process.env.APP_URL),
    },
    ssr: {
      external: [
        "node:fs",
        "node:path",
        "node:os",
        "node:crypto",
        "node:stream",
        "node:buffer",
        "node:events",
        "node:util",
        "node:assert",
        "node:zlib",
        "node:http",
        "node:https",
        "node:net",
        "node:tls",
        "node:dns",
        "node:querystring",
        "node:assert",
        "node:timers",
        "node:child_process",
        "node:cluster",
        "node:dgram",
        "node:module",
        "node:perf_hooks",
        "node:readline",
        "node:repl",
        "node:vm",
        "node:worker_threads",
        "node:fs/promises",
        "node:os",
        "node:process",
        "node:crypto",
        "node:stream",
        "node:buffer",
        "node:events",
        "node:util",
        "node:assert",
        "node:zlib",
        "node:http",
        "node:https",
        "node:net",
        "node:tls",
        "node:dns",
        "node:querystring",
        "node:assert",
        "node:timers",
        "node:child_process",
        "node:cluster",
        "node:dgram",
        "node:module",
        "node:perf_hooks",
        "node:readline",
        "node:repl",
        "node:vm",
        "node:worker_threads",
        "node:fs/promises",
        "node:os",
        "node:process",
        "node:crypto",
        "node:stream",
        "node:buffer",
        "node:events",
        "node:util",
        "node:assert",
        "node:zlib",
        "node:http",
        "node:https",
        "node:net",
        "node:tls",
        "node:dns",
        "node:querystring",
        "node:assert",
        "node:timers",
        "node:child_process",
        "node:cluster",
        "node:dgram",
        "node:module",
        "node:perf_hooks",
        "node:readline",
        "node:repl",
        "node:vm",
        "node:worker_threads",
        "node:fs/promises",
        "node:url",
        "node:stream/web",
      ],
    },
  }),
});

export default createApp({
  server: {
    preset: "vercel",
    compressPublicAssets: {
      gzip: true,
    },
  },
  routers: [
    {
      name: "public",
      type: "static",
      dir: "./public",
    },
    {
      name: "client",
      type: "client",
      handler: "./src/app/client-entry.tsx",
      target: "browser",
      base: "/_build",
      plugins: () => [tsconfigPaths(), reactRefresh(), defineConstants()],
    },
    {
      name: "ssr",
      type: "http",
      handler: "./src/app/server-entry.tsx",
      plugins: () => [tsconfigPaths(), reactRefresh(), defineConstants()],
      target: "server",
    },
    {
      name: "api",
      type: "http",
      handler: "./src/server/handler.ts",
      target: "server",
      base: "/api",
      plugins: () => [tsconfigPaths(), defineConstants()],
    },
  ],
});
